/* soapScheduleBindingProxy.h
   Generated by gSOAP 2.8.45 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapScheduleBindingProxy_H
#define soapScheduleBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC ScheduleBindingProxy : public soap {
      public:
        /// Endpoint URL of service 'ScheduleBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvif.h, if any
        /// Construct a proxy with new managing context
        ScheduleBindingProxy();
        /// Copy constructor
        ScheduleBindingProxy(const ScheduleBindingProxy& rhs);
        /// Construct proxy given a managing context
        ScheduleBindingProxy(const struct soap&);
        /// Constructor taking an endpoint URL
        ScheduleBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        ScheduleBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        ScheduleBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        ScheduleBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~ScheduleBindingProxy();
        /// Initializer used by constructors
        virtual void ScheduleBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual ScheduleBindingProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        ScheduleBindingProxy& operator=(const ScheduleBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_ns10__GetServiceCapabilities *ns10__GetServiceCapabilities, _ns10__GetServiceCapabilitiesResponse &ns10__GetServiceCapabilitiesResponse)
        { return this->GetServiceCapabilities(NULL, NULL, ns10__GetServiceCapabilities, ns10__GetServiceCapabilitiesResponse); }
        virtual int GetServiceCapabilities(const char *soap_endpoint, const char *soap_action, _ns10__GetServiceCapabilities *ns10__GetServiceCapabilities, _ns10__GetServiceCapabilitiesResponse &ns10__GetServiceCapabilitiesResponse);
        /// Web service operation 'GetScheduleState' (returns SOAP_OK or error code)
        virtual int GetScheduleState(_ns10__GetScheduleState *ns10__GetScheduleState, _ns10__GetScheduleStateResponse &ns10__GetScheduleStateResponse)
        { return this->GetScheduleState(NULL, NULL, ns10__GetScheduleState, ns10__GetScheduleStateResponse); }
        virtual int GetScheduleState(const char *soap_endpoint, const char *soap_action, _ns10__GetScheduleState *ns10__GetScheduleState, _ns10__GetScheduleStateResponse &ns10__GetScheduleStateResponse);
        /// Web service operation 'GetScheduleInfo' (returns SOAP_OK or error code)
        virtual int GetScheduleInfo(_ns10__GetScheduleInfo *ns10__GetScheduleInfo, _ns10__GetScheduleInfoResponse &ns10__GetScheduleInfoResponse)
        { return this->GetScheduleInfo(NULL, NULL, ns10__GetScheduleInfo, ns10__GetScheduleInfoResponse); }
        virtual int GetScheduleInfo(const char *soap_endpoint, const char *soap_action, _ns10__GetScheduleInfo *ns10__GetScheduleInfo, _ns10__GetScheduleInfoResponse &ns10__GetScheduleInfoResponse);
        /// Web service operation 'GetScheduleInfoList' (returns SOAP_OK or error code)
        virtual int GetScheduleInfoList(_ns10__GetScheduleInfoList *ns10__GetScheduleInfoList, _ns10__GetScheduleInfoListResponse &ns10__GetScheduleInfoListResponse)
        { return this->GetScheduleInfoList(NULL, NULL, ns10__GetScheduleInfoList, ns10__GetScheduleInfoListResponse); }
        virtual int GetScheduleInfoList(const char *soap_endpoint, const char *soap_action, _ns10__GetScheduleInfoList *ns10__GetScheduleInfoList, _ns10__GetScheduleInfoListResponse &ns10__GetScheduleInfoListResponse);
        /// Web service operation 'GetSchedules' (returns SOAP_OK or error code)
        virtual int GetSchedules(_ns10__GetSchedules *ns10__GetSchedules, _ns10__GetSchedulesResponse &ns10__GetSchedulesResponse)
        { return this->GetSchedules(NULL, NULL, ns10__GetSchedules, ns10__GetSchedulesResponse); }
        virtual int GetSchedules(const char *soap_endpoint, const char *soap_action, _ns10__GetSchedules *ns10__GetSchedules, _ns10__GetSchedulesResponse &ns10__GetSchedulesResponse);
        /// Web service operation 'GetScheduleList' (returns SOAP_OK or error code)
        virtual int GetScheduleList(_ns10__GetScheduleList *ns10__GetScheduleList, _ns10__GetScheduleListResponse &ns10__GetScheduleListResponse)
        { return this->GetScheduleList(NULL, NULL, ns10__GetScheduleList, ns10__GetScheduleListResponse); }
        virtual int GetScheduleList(const char *soap_endpoint, const char *soap_action, _ns10__GetScheduleList *ns10__GetScheduleList, _ns10__GetScheduleListResponse &ns10__GetScheduleListResponse);
        /// Web service operation 'CreateSchedule' (returns SOAP_OK or error code)
        virtual int CreateSchedule(_ns10__CreateSchedule *ns10__CreateSchedule, _ns10__CreateScheduleResponse &ns10__CreateScheduleResponse)
        { return this->CreateSchedule(NULL, NULL, ns10__CreateSchedule, ns10__CreateScheduleResponse); }
        virtual int CreateSchedule(const char *soap_endpoint, const char *soap_action, _ns10__CreateSchedule *ns10__CreateSchedule, _ns10__CreateScheduleResponse &ns10__CreateScheduleResponse);
        /// Web service operation 'ModifySchedule' (returns SOAP_OK or error code)
        virtual int ModifySchedule(_ns10__ModifySchedule *ns10__ModifySchedule, _ns10__ModifyScheduleResponse &ns10__ModifyScheduleResponse)
        { return this->ModifySchedule(NULL, NULL, ns10__ModifySchedule, ns10__ModifyScheduleResponse); }
        virtual int ModifySchedule(const char *soap_endpoint, const char *soap_action, _ns10__ModifySchedule *ns10__ModifySchedule, _ns10__ModifyScheduleResponse &ns10__ModifyScheduleResponse);
        /// Web service operation 'DeleteSchedule' (returns SOAP_OK or error code)
        virtual int DeleteSchedule(_ns10__DeleteSchedule *ns10__DeleteSchedule, _ns10__DeleteScheduleResponse &ns10__DeleteScheduleResponse)
        { return this->DeleteSchedule(NULL, NULL, ns10__DeleteSchedule, ns10__DeleteScheduleResponse); }
        virtual int DeleteSchedule(const char *soap_endpoint, const char *soap_action, _ns10__DeleteSchedule *ns10__DeleteSchedule, _ns10__DeleteScheduleResponse &ns10__DeleteScheduleResponse);
        /// Web service operation 'GetSpecialDayGroupInfo' (returns SOAP_OK or error code)
        virtual int GetSpecialDayGroupInfo(_ns10__GetSpecialDayGroupInfo *ns10__GetSpecialDayGroupInfo, _ns10__GetSpecialDayGroupInfoResponse &ns10__GetSpecialDayGroupInfoResponse)
        { return this->GetSpecialDayGroupInfo(NULL, NULL, ns10__GetSpecialDayGroupInfo, ns10__GetSpecialDayGroupInfoResponse); }
        virtual int GetSpecialDayGroupInfo(const char *soap_endpoint, const char *soap_action, _ns10__GetSpecialDayGroupInfo *ns10__GetSpecialDayGroupInfo, _ns10__GetSpecialDayGroupInfoResponse &ns10__GetSpecialDayGroupInfoResponse);
        /// Web service operation 'GetSpecialDayGroupInfoList' (returns SOAP_OK or error code)
        virtual int GetSpecialDayGroupInfoList(_ns10__GetSpecialDayGroupInfoList *ns10__GetSpecialDayGroupInfoList, _ns10__GetSpecialDayGroupInfoListResponse &ns10__GetSpecialDayGroupInfoListResponse)
        { return this->GetSpecialDayGroupInfoList(NULL, NULL, ns10__GetSpecialDayGroupInfoList, ns10__GetSpecialDayGroupInfoListResponse); }
        virtual int GetSpecialDayGroupInfoList(const char *soap_endpoint, const char *soap_action, _ns10__GetSpecialDayGroupInfoList *ns10__GetSpecialDayGroupInfoList, _ns10__GetSpecialDayGroupInfoListResponse &ns10__GetSpecialDayGroupInfoListResponse);
        /// Web service operation 'GetSpecialDayGroups' (returns SOAP_OK or error code)
        virtual int GetSpecialDayGroups(_ns10__GetSpecialDayGroups *ns10__GetSpecialDayGroups, _ns10__GetSpecialDayGroupsResponse &ns10__GetSpecialDayGroupsResponse)
        { return this->GetSpecialDayGroups(NULL, NULL, ns10__GetSpecialDayGroups, ns10__GetSpecialDayGroupsResponse); }
        virtual int GetSpecialDayGroups(const char *soap_endpoint, const char *soap_action, _ns10__GetSpecialDayGroups *ns10__GetSpecialDayGroups, _ns10__GetSpecialDayGroupsResponse &ns10__GetSpecialDayGroupsResponse);
        /// Web service operation 'GetSpecialDayGroupList' (returns SOAP_OK or error code)
        virtual int GetSpecialDayGroupList(_ns10__GetSpecialDayGroupList *ns10__GetSpecialDayGroupList, _ns10__GetSpecialDayGroupListResponse &ns10__GetSpecialDayGroupListResponse)
        { return this->GetSpecialDayGroupList(NULL, NULL, ns10__GetSpecialDayGroupList, ns10__GetSpecialDayGroupListResponse); }
        virtual int GetSpecialDayGroupList(const char *soap_endpoint, const char *soap_action, _ns10__GetSpecialDayGroupList *ns10__GetSpecialDayGroupList, _ns10__GetSpecialDayGroupListResponse &ns10__GetSpecialDayGroupListResponse);
        /// Web service operation 'CreateSpecialDayGroup' (returns SOAP_OK or error code)
        virtual int CreateSpecialDayGroup(_ns10__CreateSpecialDayGroup *ns10__CreateSpecialDayGroup, _ns10__CreateSpecialDayGroupResponse &ns10__CreateSpecialDayGroupResponse)
        { return this->CreateSpecialDayGroup(NULL, NULL, ns10__CreateSpecialDayGroup, ns10__CreateSpecialDayGroupResponse); }
        virtual int CreateSpecialDayGroup(const char *soap_endpoint, const char *soap_action, _ns10__CreateSpecialDayGroup *ns10__CreateSpecialDayGroup, _ns10__CreateSpecialDayGroupResponse &ns10__CreateSpecialDayGroupResponse);
        /// Web service operation 'ModifySpecialDayGroup' (returns SOAP_OK or error code)
        virtual int ModifySpecialDayGroup(_ns10__ModifySpecialDayGroup *ns10__ModifySpecialDayGroup, _ns10__ModifySpecialDayGroupResponse &ns10__ModifySpecialDayGroupResponse)
        { return this->ModifySpecialDayGroup(NULL, NULL, ns10__ModifySpecialDayGroup, ns10__ModifySpecialDayGroupResponse); }
        virtual int ModifySpecialDayGroup(const char *soap_endpoint, const char *soap_action, _ns10__ModifySpecialDayGroup *ns10__ModifySpecialDayGroup, _ns10__ModifySpecialDayGroupResponse &ns10__ModifySpecialDayGroupResponse);
        /// Web service operation 'DeleteSpecialDayGroup' (returns SOAP_OK or error code)
        virtual int DeleteSpecialDayGroup(_ns10__DeleteSpecialDayGroup *ns10__DeleteSpecialDayGroup, _ns10__DeleteSpecialDayGroupResponse &ns10__DeleteSpecialDayGroupResponse)
        { return this->DeleteSpecialDayGroup(NULL, NULL, ns10__DeleteSpecialDayGroup, ns10__DeleteSpecialDayGroupResponse); }
        virtual int DeleteSpecialDayGroup(const char *soap_endpoint, const char *soap_action, _ns10__DeleteSpecialDayGroup *ns10__DeleteSpecialDayGroup, _ns10__DeleteSpecialDayGroupResponse &ns10__DeleteSpecialDayGroupResponse);
    };
#endif
