/* soapThermalBindingProxy.h
   Generated by gSOAP 2.8.45 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapThermalBindingProxy_H
#define soapThermalBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC ThermalBindingProxy : public soap {
      public:
        /// Endpoint URL of service 'ThermalBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvif.h, if any
        /// Construct a proxy with new managing context
        ThermalBindingProxy();
        /// Copy constructor
        ThermalBindingProxy(const ThermalBindingProxy& rhs);
        /// Construct proxy given a managing context
        ThermalBindingProxy(const struct soap&);
        /// Constructor taking an endpoint URL
        ThermalBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        ThermalBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        ThermalBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        ThermalBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~ThermalBindingProxy();
        /// Initializer used by constructors
        virtual void ThermalBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual ThermalBindingProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        ThermalBindingProxy& operator=(const ThermalBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_ns11__GetServiceCapabilities *ns11__GetServiceCapabilities, _ns11__GetServiceCapabilitiesResponse &ns11__GetServiceCapabilitiesResponse)
        { return this->GetServiceCapabilities(NULL, NULL, ns11__GetServiceCapabilities, ns11__GetServiceCapabilitiesResponse); }
        virtual int GetServiceCapabilities(const char *soap_endpoint, const char *soap_action, _ns11__GetServiceCapabilities *ns11__GetServiceCapabilities, _ns11__GetServiceCapabilitiesResponse &ns11__GetServiceCapabilitiesResponse);
        /// Web service operation 'GetConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetConfigurationOptions(_ns11__GetConfigurationOptions *ns11__GetConfigurationOptions, _ns11__GetConfigurationOptionsResponse &ns11__GetConfigurationOptionsResponse)
        { return this->GetConfigurationOptions(NULL, NULL, ns11__GetConfigurationOptions, ns11__GetConfigurationOptionsResponse); }
        virtual int GetConfigurationOptions(const char *soap_endpoint, const char *soap_action, _ns11__GetConfigurationOptions *ns11__GetConfigurationOptions, _ns11__GetConfigurationOptionsResponse &ns11__GetConfigurationOptionsResponse);
        /// Web service operation 'GetConfiguration' (returns SOAP_OK or error code)
        virtual int GetConfiguration(_ns11__GetConfiguration *ns11__GetConfiguration, _ns11__GetConfigurationResponse &ns11__GetConfigurationResponse)
        { return this->GetConfiguration(NULL, NULL, ns11__GetConfiguration, ns11__GetConfigurationResponse); }
        virtual int GetConfiguration(const char *soap_endpoint, const char *soap_action, _ns11__GetConfiguration *ns11__GetConfiguration, _ns11__GetConfigurationResponse &ns11__GetConfigurationResponse);
        /// Web service operation 'SetConfiguration' (returns SOAP_OK or error code)
        virtual int SetConfiguration(_ns11__SetConfiguration *ns11__SetConfiguration, _ns11__SetConfigurationResponse &ns11__SetConfigurationResponse)
        { return this->SetConfiguration(NULL, NULL, ns11__SetConfiguration, ns11__SetConfigurationResponse); }
        virtual int SetConfiguration(const char *soap_endpoint, const char *soap_action, _ns11__SetConfiguration *ns11__SetConfiguration, _ns11__SetConfigurationResponse &ns11__SetConfigurationResponse);
    };
#endif
